plugins:
  kubeflow/katib:
  - trigger
  kubeflow/kfctl:
  - trigger
  kubeflow/kubeflow:
  - trigger
  kubeflow/manifests:
  - trigger
  kubeflow/pytorch-operator:
  - trigger
  kubeflow/xgboost-operator:
  - trigger